-- INSERT INTO weathers (name, temperature, condition, humidity, wind_speed) VALUES
--                                                                              ('Minsk', -5.0, 'Snow', 80.0, 5.0),
--                                                                              ('Saint Petersburg', 2.5, 'Cloudy', 65.0, 3.5),
--                                                                              ('Tokyo', -10.0, 'Clear', 50.0, 2.0),
--                                                                              ('Tbilisi', 0.0, 'Rain', 90.0, 4.0),
--                                                                              ('Paris', -3.0, 'Snow', 70.0, 6.0);
--
-- INSERT INTO forecasts (name, date, temperature_min, temperature_max, condition) VALUES
--                                                                                   ('Minsk', '2025-04-08', -7.0, -2.0, 'Snow'),
--                                                                                   ('Saint Petersburg', '2025-04-08', 0.0, 4.0, 'Cloudy'),
--                                                                                   ('Tokyo', '2025-04-08', -12.0, -8.0, 'Clear'),
--                                                                                   ('Tbilisi', '2025-04-08', -1.0, 3.0, 'Rain'),
--                                                                                   ('Paris', '2025-04-08', -4.0, 0.0, 'Snow');
